- name: Create mosquitto group
  group:
    name: mosquitto
    system: yes
  tags:
    - mqtt

- name: Create mosquitto user
  user:
    name: mosquitto
    create_home: no
    shell: /sbin/nologin
    home: /var/empty
    system: yes
  tags:
    - mqtt
    - mqtt_config
  register: userinfo

- name: Create MQTT directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mqtt_user }}"
    group: "{{ mqtt_group }}"
    mode: '0755'
  loop: "{{ mqtt_directories }}"
  tags:
    - mqtt
    - mqtt_config

- name: Create empty MQTT files for use by the running container
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ mqtt_user }}"
    group: "{{ mqtt_group }}"
    mode: '0644'
  loop: "{{ mqtt_touch_files }}"
  tags:
    - mqtt_config

- name: Copy MQTT config files
  template:
    src: "{{ item.name | default(item) }}"
    dest: "{{ mqtt_data_dir }}/config/{{ item.name | default(item) | splitext | first }}"
    backup: yes
    owner: "{{ mqtt_user }}"
    group: "{{ mqtt_group }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ mqtt_config_files | flatten(levels=1) }}"
  notify: restart mqtt container
  tags:
    - mqtt
    - mqtt_config

- name: Check if ports should be published 
  set_fact:
      mqtt_container_exposed_ports: ""
  when: mqtt_container_publish_ports is true
  tags:
    - mqtt
    - mqtt_config

- name: Check if ports should be only exposed
  set_fact:
      mqtt_container_published_ports: ""
  when: mqtt_container_publish_ports is false
  tags:
    - mqtt
    - mqtt_config

- name: Pull MQTT docker image
  docker_image:
    name: "{{ mqtt_image_name + ':' + mqtt_image_version }}"
    source: pull
  register: image_update
  tags:
    - mqtt

- name: Run MQTT container
  docker_container:
    name: "{{ mqtt_container_name }}"
    image: "{{ mqtt_image_name + ':' + mqtt_image_version }}"
    user: "{{ userinfo.uid }}:{{ userinfo.group }}"
    network_mode: "{{ mqtt_container_network_mode }}"
    restart_policy: "{{ mqtt_container_restart_policy }}"
    state: started
    published_ports: "{{ mqtt_container_published_ports | default(omit, true) }}" 
    exposed_ports: "{{ mqtt_container_exposed_ports | default(omit, true) }}"
    networks: "{{ mqtt_container_networks | default(omit) }}"
    volumes: "{{ mqtt_container_volumes }}"
    labels: "{{ mqtt_container_labels | default(omit) }}"
  tags:
    - mqtt
