- name: Include variables for {{ mqtt_installation_method }} installation
  include_vars: "{{ mqtt_installation_method }}.yml"
  tags:
    - always

- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.os_distribution }}.yml"
    - defaults/main.yml
  tags:
    - always

- include_tasks: "{{ mqtt_installation_method }}.yml"
  tags:
    - mqtt
    - mqtt_config
