- include_tasks: "install-{{ ansible_facts.os_family }}.yml"
  tags:
    - mqtt

- name: Copy MQTT config files
  template:
    src: "{{ item.name | default(item) }}"
    dest: "{{ item.name | default(item) | splitext | first }}"
    backup: true
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ mqtt_config_files }}"
  notify: restart mqtt
  tags:
    - mqtt
    - mqtt_config

- name: Start and enable mosquitto service
  service:
    name: "{{ mqtt_service_name }}"
    state: started
    enabled: true
  register: service_start
  tags:
    - mqtt
