- name: Verify role
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure mosquitto is working
      command: mosquitto_pub -i ansible -t 'testtopic' -m 'testing' -h localhost -p 1883
